### ISSUE TITLE
rke2/k3s data collection

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/support-bundle-kit#128]
Currently there is no easy way to get state of a remote rke2/k3s cluster, which makes troubleshooting complicated.

We need collectors for rke2/k3s along with a way to run support-bundle-kit from the command line to allow data to be collected from a target cluster.

**Comment by innobead** [comment]
Let's track the issue at Harvester to make it align with the release, https://github.com/harvester/harvester/issues/7113. 

cc @bk201 @rebeccazzzz
