### ISSUE TITLE
Allow specifying agent DaemonSet node selectors

### ISSUE THREAD

**Issue by bk201** [rancher/support-bundle-kit#18]
The node selector of the agent DaemonSet is hard-coded to` "node-role.kubernetes.io/worker"="true"`.
https://github.com/rancher/support-bundle-kit/blob/ccd9e56134756f51f5b0680bc1604c913c4d7f84/pkg/manager/agent.go#L69

It's not suitable for all use cases (e.g. Harvester nodes). We need a way to specify the selectors.

**Comment by yasker** [comment]
Done
