### ISSUE TITLE
Some resource are not stored because resource name conflict

### ISSUE THREAD

**Issue by bk201** [rancher/support-bundle-kit#19]
I'm testing the auto-discovery feature in Harvester cluster, some resources are not stored because their names are the same.

e.g.: these two CRs have the same resource name `settings`:
- settings.harvesterhci.io
- settings.management.cattle.io

Only `settings.management.cattle.io` manifests are stored with `settings.yaml` file in the support bundle.

The cause should be we use the resource name as key and it's overwritten by the last-discovered resource.
https://github.com/rancher/support-bundle-kit/blob/8ef53fba19dc49bc4c9aa6ece34ad9d187c4dad0/pkg/manager/client/discovery.go#L119

https://github.com/rancher/support-bundle-kit/blob/8ef53fba19dc49bc4c9aa6ece34ad9d187c4dad0/pkg/manager/client/discovery.go#L168

We need a key that is unique in the cluster.

Version: 8ef53fba19dc49bc4c9aa6ece34ad9d187c4dad0

**Comment by yasker** [comment]
@bk201 The fix has been merged, can you check?

**Comment by bk201** [comment]
> @bk201 The fix has been merged, can you check?

The YAML files look good now, thanks for the fix @shangma 
For reference, here is a bundle.
[supportbundle_c9eafbd9-6984-463f-b34c-af3ca8bdb085_2021-09-04T02-47-18Z.zip](https://github.com/rancher/support-bundle-kit/files/7109129/supportbundle_c9eafbd9-6984-463f-b34c-af3ca8bdb085_2021-09-04T02-47-18Z.zip)
