### ISSUE TITLE
Expect to have logs of kubelet and other k8s components

### ISSUE THREAD

**Issue by w13915984028** [rancher/support-bundle-kit#36]
Kubelet has following logs, it explians why a POD is restarted in detail, expect it is included in support bundle.

Logs of other k8s components, need to be checked case by case.

`E0414 12:54:28.776157    2021 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-09e84c10-33ab-4e74-9a31-0373b3cf97e6 podName: nodeName:}" failed. No retries permitted until 2022-04-14 12:54:29.776137295 +0000 UTC m=+45.118023510 (durationBeforeRetry 1s). Error: "MountVolume.MountDevice failed for volume \"pvc-09e84c10-33ab-4e74-9a31-0373b3cf97e6\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-09e84c10-33ab-4e74-9a31-0373b3cf97e6\") pod \"prometheus-rancher-monitoring-prometheus-0\" (UID: \"35d51fd3-c88d-4750-b569-1aa443bc6885\") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name driver.longhorn.io not found in the list of registered CSI drivers"`

**Comment by bk201** [comment]
kubelet.log will be collected after: https://github.com/rancher/support-bundle-kit/pull/38

**Comment by bk201** [comment]
@w13915984028 is #38 good enough to close this issue? Thanks!

**Comment by w13915984028** [comment]
Feature is added. Thanks.
